name: labelaction

on:
  issues:
    types:
      - opened
      - edited

jobs:

  label_issue:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: oras-project/setup-oras@v1
        with:
          version: 1.0.0

      - name: label issue
        env:
          GH_EVENT: ${{ toJSON(github.event) }}
          GH_TOKEN: ${{ github.token }}
        run: |
          cd scripts
          rm -f issueci.sh
          oras pull ghcr.io/liangyuanpeng/blog:issuecish
          chmod +x ./issueci.sh  
          ./issueci.sh